language: go
go:
  - 1.8.x
script:
  - make test
before_deploy:
  - make dist
deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
